from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

bot = ChatBot(
    'Norman',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database='./personal-chat.sqlite3'
)
bot.set_trainer(ListTrainer)
#Training starts here
bot.train(["Bar",
"kahi",
"nahi ali athvan",
"Acha",
"aadhi lab madhe project karun aalo",
"shift kartoy",
"me pan",
"ohh",
"Aali ka athvn",
"College mdhe ahe",
"whats up",
"heyy",
"Thanks",
"Ok",
"khup adds astat",
"just to be safe",
"and install avast antivirus first",
"but keep ur addblock on",
"if you want you can also sign up",
"123Movies",
"rohitbhalchandras@gmail.com",
"https://123movies.cafe",
"Ho",
"hach point hota to",
"athvte ka ? jevha rasta sampla hota",
"Rupal called you.",
"Bar",
"I look forward type kahitari",
"Closing line sang na",
"You missed a video chat with Rupal.",
"You missed a video chat with Rupal.",
"Bol",
"Janeman",
"Ho",
"Uthla ka janeman",
"Tata",
"Tu kr abhyas",
"Kha pot bhar",
"Okay",
"Khaun jate",
"Ata pizza order kela ahe",
"Ghari jaa mag",
"Okay",
"Zali party",
"Party madhe",
"Aata tithe laksha de",
"Ho",
"Ghari gelyavar call kar",
"Ha",
"Mag aaram Kar ghari jaun",
"Bar vatat nahiye",
"I m not enjoying",
"Baghu",
"Tu enjoy kar",
"Aramat",
"Nantar ye",
"Bye",
"Asch mhanali",
"Jaude",
"Hmmm",
"Visa la 2-3 weeks lagtat approve vhayla",
"Are Feb aala",
"Kay ushir ?",
"1-2 divsat apply Karun taku",
"Ushir kela vatate",
"I miss u alot",
"Hmm",
"Lavkarat lavkar",
"Chalte re pan pahile visa vhav lagel na",
"La to Vancouver",
"Kuthe??",
"Chalte ka ?",
"15k cha return ticket ahe",
"Okay",
"I will ask rahul also",
"Ha thik ahe",
"Velch nahi milat",
"Karu",
"Parva",
"I m so tired",
"Nahi yar...Career fair ahe udya",
"Aani apply Karun taku visa sathi",
"Dogha milun visa cha search karu",
"Ka",
"Divs bhar",
"Udya free kadhi aahes",
"ð",
"I miss u",
"Acha",
"Visa cha karu aadhi",
"1 month mdhe paise jamtil mazyakade",
"I don't wanna be with them on bday",
"Tu yeshil ka 4 la",
"Me too",
"I miss u",
"Ha",
"Carry on",
"Okay",
"Abe",
"Sagle jamle ahet",
"Bday ahe na tya poracha",
"Kay karayli",
"ð",
"Kahihi ha shree",
"ð",
"Mala haklun deti bed Varun tu",
"Lagti",
"Mala evdhi jaga nahi lagat",
"ð",
"The video chat ended.",
"You and Rupal can now see each other.",
"Rupal started sharing video.",
"??",
"Video call",
"Ha",
"Mast aaram Kar ghari basun",
"Adhun mdhun vomiting sarkh hotay",
"Kahi hot nahi",
"Ani weakness",
"Chest pain",
"Headache",
"Mazya roommates la pan first week la zalela",
"Sardi tap nahiye",
"Ha",
"Asach thoda far sardi tap asel",
"Kahi major nasel",
"Acha",
"So don't worry",
"US Canada",
"Aani ikde jasti aajari nahi padat loka",
"Gharunch sangtat",
"Aaj rest krte baghu thik vatal tr",
"Aani tyala sangayla lavto",
"Ajun nako",
"Tyancha number deto tula",
"Tar siddhesh chi aaie Dr aahe",
"Samjat",
"Aani Tula nasel samajti tar",
"Bghte",
"Ha",
"So goli vagaire ghe",
"Admit asashil tarch jasti miltat",
"Tcs wale 6k ch detat",
"TCS cha valid ahe ka bghav lagel",
"Temporarily",
"Ha",
"TCS cha aasel",
"Ithe yeun apply kela",
"Nahi",
"Apply kelyavr 2-3 month mdhe yeto",
"India madhunch kadhla asashil na",
"Mhanje",
"Nahi aala ajun insurance",
"Body temperature pn low ahe",
"Tuza insurance kadhlay na tu",
"Lagech",
"Doctor Kade jaun ye",
"Headache",
"Abe be",
"Weakness",
"Khokla",
"N chest pain",
"Ha",
"Be",
"Thandi vajayli ka",
"Not sure though",
"I might hv pneumonia",
"You missed a call from Rupal.",
"Aalo",
"Shift la aali",
"Take care",
"Ohh",
"Sorry sadhya khup chidchid krte",
"Uthli me",
"Abe shift la aalo na",
"Me msg krtach offline gela",
"Bye",
"J1 Karun bolu",
"Mala jevaycha",
"And there is no way Tula serious nahi vatnar",
"Bye",
"Jaude",
"But I was not serious",
"Tula serious banun mhanalo",
"Nahi be",
"Ata palatla",
"Tu tevha serious hota",
"Itkach vatat asel tar nahi mhananar nantr",
"Don't take it that serious",
"ð",
"Aane te asach mhanalo hoto",
"Me Kahi fukat nahiye",
"Ho na",
"Abe mala pn Kam astat",
"Tu Baki lokanshi WhatsApp var bolat hoti",
"Athv",
"Tuch bolat hota asa",
"Tuzya case madhe",
"Kahi pan ka",
"Tu apla",
"Chatting window opench aahe",
"Ki vate kashe karu",
"Roommate na bhaji cha v4 la",
"Bye",
"Kr Kay kraych te",
"Me tuzyashich bolat hoto",
"Aatach shift Karun aaloy",
"I m serious",
"Jevaycha mala",
"I will do d same",
"Bore nako karu be",
"Me lakshat thevel",
"Sahi h",
"Ata lgech bye",
"Bye",
"Sagle rules mala lavun Dile ahet tu",
"I m not chatting with someone",
"Bhand kartay te",
"La boltoy",
"Tu bol mala Kahi next time",
"Are roommate",
"Thamb beta",
"Ata read krun reply krena",
"Kunala bolat hpta",
"Khupch Bor zal seriously",
"Bore kartoy",
"Asach",
"Abe",
"Kay zal",
"Kshala reverse lihit ahe",
"Acha",
"Dok firal tuza program krun krun",
"Ak ihan mak ihak",
"Te programmer vr sarcasm wale post astat na tasa behave krayla",
"Alas uhc",
"Kahi Kam nahi ka",
"Chu sala",
"Reverse type kela",
"Abe chu",
"Hahaha",
"Abe piun type krtoy ka",
"Samjla nahi ka",
"Ek gnittahc gM",
"Kay brltoy",
"Enahm seitiroirp Alam inA",
"Uhc",
"Chu",
"Ani mala priorities mhane",
"Mg chatting kr",
"Pahile mala bolto ka",
"Mhnje",
"Lob",
"Bol",
"Kay",
"Oy",
"Ok",
"ho",
"Ahe ka ol",
"Hi",
"Kr tuz kam",
"Bye",
"Love me love me say that u love me",
"Vaa vaa",
"Dil k Arman asuo me beh gaye",
"No I don't",
"ð",
"U don't miss me",
"Yo",
"Kha",
"Acha",
"Mala bhuk lagli khato kahitri",
"Maniyar",
"Are te bhaji Kashi karaychi v4at hota",
"Ok",
"Ohhh",
"Internship application karaychet",
"Ata tu kunala priorities detoy be",
"Hat re",
"Kahitari new",
"Porasobt jaun ye strip club la",
"Kahitari",
"Gharich TP",
"New year cha kay plan ahe",
"Kay kel mg",
"Ohh",
"ðð",
"Tyala hook samorun ahe",
"Rohit tula easy",
"Ha",
"Summer madhe",
"Aata nahi ghalta yenar",
"Thandi  aaste ikda",
"Aacha",
"ðð»",
"Pn beach vr ghalaysathi pahile Purn  saf safai kravi lagel",
"Shabbas",
"Vaaa",
"ð",
"Bol na halke halke",
"Me khupch sexy wali bra ghetli",
"Gana nahi mahit ka",
"Kay",
"ðð",
"Halke halke",
"Bol na",
"Vaa",
"Ohh",
"Ata uthli",
"Kam nahit ka",
"Bye",
"Bye",
"Hao",
"Mag parat abhyas kafaychay",
"Me karto thoda tp",
"Kahi lagal tr sang",
"Ok",
"Acha",
"Extra",
"Paise tr bharave lagtil na",
"Tuition fees madhe",
"Baba pathavtay",
"Credit vr ghetla na",
"??",
"Sadhya sagal thik chalu ahe",
"Paise kashala",
"Okay",
"Dusar Kahi nahi",
"Risk nahi gheu vatat be",
"Paise lagnar ahe ka ?",
"??",
"Video call",
"Han me credit card var ghetla",
"Tuzi pan titkich aahe na",
"?",
"Tu credit ne ghetla ka laptop",
"Aahe",
"mazi 4 gb",
"Let it be",
"Anyway",
"RAM pn kami ahe mazi",
"Then it's all good to go",
"Bas",
"2000rs chi battery",
"Nothing else",
"Mazya hyala pan battery problem aahe",
"Tu abhyas kr",
"Chan",
"Maza chalto",
"Battery problem ahe pn tyala",
"Ani jastch tras hot asel tar maza pathavto",
"Hao chalte thoda far",
"Mag navin ghe",
"Kasabasa",
"Ek semester kadh",
"Abe tuza kamapurta chalte ka",
"Nahi pahije be",
"If u don't want to invest money on laptop",
"I can parcel it to you",
"For small usage",
"I don't want ur laptop",
"It works good",
"I can give it to u",
"If u need it then",
"Ha",
"Bara",
"Vaparlela",
"But padun rahnyapeksha",
"Tashi garaj nasel",
"Ho",
"2-2 vaprnar ka",
"No",
"??",
"Why u want it",
"Juna vaprel na",
"Urs doesn't work",
"Junyach Kay krnar ahe tu ?",
"Ghe",
"Yup",
"Me pn navin laptop gheu ka",
"Haan",
"Thik h",
"Gharich basun",
"Gap enjoy kar",
"Be",
"Kashala dagdag",
"Jau ka",
"4 days to go",
"Muku Hyderabad la bolvt ahe",
"Haan",
"Changla abhyas kr",
"Haha",
"Ghrche pahtil tr problem hoel na be",
"Pyar Kiya toh darna kya",
"Kaa",
"ð",
"Tuze photo lapvat hoti",
"Kahi nahi",
"Zop aramat",
"Tuza Kay chaluye",
"Tc",
"Acha",
"Ka dukhatay nahi mahit",
"Tension nahiye",
"Nahi",
"Sakali sakali uthlya uthlya",
"2 da",
"Tension ala ka",
"Golya ghyavya laglya",
"Kskay",
"Aaj",
"Doka khup dukhat hota",
"Enjoy",
"Ohhh",
"Aata 2 nch rahilet",
"Lecture baghun zale",
"Zala ka abhyas",
"Yo",
"?",
"Ol",
"You missed a video chat with Rupal.",
"The video chat ended.",
"The video chat ended.",
"Ok",
"We can talk",
"If u r at home by that time",
"Me ghari 9:30 means tuze 10AM paryant jail",
"Abhyas kr",
"So can't have a call",
"I m in lecture",
"Oh",
"Ata uthli",
"whats up",
"babes",
"heyy",
"You called Rupal.",
"Me office chi tayari krte",
"Aaie shi Boltoy",
"Ushir zala br",
"Uthli",
"You missed a call from Rupal.",
"utha utha ho sakalika",
"ð",
"Ttul",
"Bbye",
"Kar kam",
"Gn",
"Bye",
"Hhan",
"Zop tu",
"Rahu de",
"Net prob ahe be",
"ð§",
"Mazyasathi time nahi mhnti",
"30 min zale",
"Itka vel ?",
"Rugya la boltoy",
"ð",
"Rupal called you.",
"I should probably hire someone for sex",
"I don't like masturbation",
"Plz",
"Switch to whatsapp",
"ð",
"Aani zop yeil changli",
"Thakshil",
"Masterbation Kar mag",
"Ewww",
"ð",
"As a result, khup pimples yetay",
"Mala zop nahi lagat sadhya",
"I can't Rohit even if I want to",
"U will enjoy there",
"Aani go for Bangalore trip",
"2 vajlet",
"Zop be",
"Babe",
"What do you think",
"Rupal",
"Plus v need money right now",
"I can see banglore later",
"Plus leaves too",
"7-8k vachtil",
"I m thinking to cancel banglore trip n give some excuse",
"Bye",
"Hmm",
"ðð»",
"Please",
"Please don't make it hard on urself",
"Bye",
"Just sleep",
"No worries",
"Udya bolu",
"Job sapdayla",
"Cafe la jaychay",
"Zopi jaa",
"As of now",
"Okay",
"Mala nahi mahit",
"Kay upay",
"Kahi upay",
"Aare work around mhanje",
"My work has nothing to do with this",
"So that u won't be mad at me",
"Are try to find some work around",
"What do you want me to do Rohit",
"Ki apoap vait vatate",
"Tula nahi bolalo",
"Abe yar",
"I didn't wanted to make you feel bad",
"Swath pan radtiye aani mala pan",
"But don't cry on it",
"I did joparyant possible hot",
"Are aahe tough manya aahe",
"I m going through the tough phase so it's hard to pretend everything is fine",
"Abhyasat man nahi lagat",
"But bhandanamule",
"Tension nahi",
"Mag tech hotay na",
"I don't want to increase ur tension Rohit",
"2 vrsh",
"Thoda tar tolerance rahava",
"10 divs nahi yar",
"Aani bhandan literally 4thya divsapasun kela yar",
"I m not shouting on u",
"You judge based on just 10 days",
"But I m not ready for u to shout on me",
"I am ready for challenge",
"Aare ho",
"Manus settle pan nahi zala nit",
"You knew this would happen n u Choose it",
"He khup tensions aahet",
"Interview sathi",
"1 kacha reply alela",
"Aata paryant 30 part time Sathi apply kelay",
"Mala mazach padlela",
"From our University",
"Yah 1000 people in just CS",
"In 1000 people",
"Don't know how I m gonna survive",
"Don't know about future",
"Aani gharchyana aata paise magayle laj vatate",
"Part time aajun nahi milalela",
"First month madhe mala 1000$ laglet",
"Me 12 lakh loan gheun aaloy itha",
"Action speaks louder than words",
"Look",
"Nd u should consider that too",
"But there is always other side",
"On their behavior",
"U judge people",
"Except the last 15 days when you were leaving",
"I feel u say love me but most of the time I couldn't see it in ur actions",
"But",
"There's no good way to say this",
"But we have some time to think upon it",
"As of now we r officially broke",
"So it's my advice ki v4 kar",
"And want break up",
"Not like u r mad",
"And with thinking",
"You should take decision carefully",
"But that won't work either",
"I could have given you some time to observe",
"But u can take time to decide as well",
"If u have decided then it's okay",
"Then",
"I don't want regrets",
"Okkay",
"N I don't want to cry entire life",
"I m scared, u won't be able to make me happy",
"So it's different",
"Urlele 118 hours sobat astol",
"Don't teach me math",
"Aani tyapaiki fakt 50 hours kamat jatat",
"Week madhe 168 hours astat",
"Yar",
"Tenvha sobat astol",
"Be",
"Nahi ve",
"After two years, u will be like Ayush ahe romance krayla but this meeting is very imp etc etc",
"Aata patliye and this time is very crucial thoda slow ghetla Tari chalel",
"But I m a kind of high maintenance",
"Me tasa nahi mhanalela",
"I m not proud of saying this",
"It's not like aata patli so kasahi chalel",
"If someone wants to be with me, he has to make efforts entire life",
"N",
"Rohit I have been thinking already",
"Decision",
"Not like tadkafadki",
"And then decide",
"Think about it",
"Take a break",
"And if u want a solution",
"Ugi gap Zopi jaa",
":(",
"I m sorry",
"I m not as good as u",
"I m not like u to forget everything with good conversation",
"I m trying to find permanent solution",
"I m not fighting with u",
"Not today",
"So u r not going to talk to me again?",
"Bbye",
"Mala kahi nahi pahihe",
"What do you want Rohit",
"Doesn't seem like it",
"Taking u seriously",
"I m",
"Y u never take me seriously ?",
"Happy weekend ahead",
"Bye",
"Zopi jaa",
"Gap ki",
"So I will be able to know what's going on with u",
"But keep updating",
"Tabyet kharab aahe ka",
"I know Tula FB vaprayla nahi avdt",
"Ka nahi geli",
"Nahi geli aaj",
"Office madhe",
"Kay kela aaj divas bhar",
"Yah",
"So this is it ?",
"I mean it",
"R u just saying this to make me sleep or u mean it ?",
"Gn",
"Bye",
"Ohhkay",
"This will be good for everybody",
"So just let me go when I can",
"My existence will do nothing other than ruining ur future",
"I m totally screwed up",
"You deserve better than me",
"You are a good person Rohit",
"okay",
"Stop texting me",
"I don't want to talk to you",
"Gm",
"Zoptoy me",
"Hii",
"Zala ki nahi rag shant",
"400$ aale vapas",
"ð",
"Messenger var nahi kela blocj",
"Ok",
"Acha",
"ð",
"Me kahi joke nahi karat aahe",
"Sunsan rastyane rupal",
"ððð",
"Rastyane nahi jau tr udat jau ka",
"Sun San rastyane nako jat jau",
"Tashi traffic mhant nahiye",
"Hahha",
"ð",
"Traffic madhe accident hoto mg",
"Mhanun traffic aslelyach road ne jat jaa",
"Acha",
"Ohhh",
"They tried to rape that girl",
"Mhnje?",
"So try avoiding empty roads",
"Vinaybhang zala",
"He kay",
"Happy journey",
"Ok",
"Aani udya gavakde mandirat jaychay",
"Ghari saman takun yaycha",
"Mg travel kshala krto.. Aram kar",
"Sardi tap ghasa dukhtoy",
"Tabyet kharab aahe mazi",
"N u don't like me",
"Aare yar",
"U don't break up with me",
"U don't hv time for me",
"Zala kay",
"??",
"Kay feeling",
"Abe yar",
"Don't play with someone's feeling",
"Aata uthlo na be",
"Zoplo hoto",
"U r cheating on me",
"Liar",
"Zopla mhnto khota",
"Kay",
"OK",
"Pohonchlo room var",
"Kadhi",
"?",
"kunala msg karat hota be",
"Sorry Yar bahut din se teko Mera lund nahi mila muh Mai leneko",
"ðð",
"bye",
"Will call u after I reach on station",
"Ho",
"jau ka offline ?",
"Bye",
"Thik aahe",
"Acha ASA ka",
"happy joourney",
"chal bye",
"maze tr nahich nahi tuze pn nahi",
"cool tr te astat je mhntat ki tumch vay ahe..enjoy",
"Bar",
"Pay",
"kahi cool nahie",
"hat",
"ð",
"Cool aahet mahacool nahit",
"tuch tr mhnto tuze gharche khup cool ahe bla bla bla",
"Har 5 min la call",
"Me ghari aaahe",
"Mag Tula nahi Kalat ka",
"katti",
"ragvat rahto nehmi",
"Rahu de baba",
"baghitala na",
"Lai kamat disayli baya",
"Baghena bi zali tu tar msgs",
"call kela tevha kiti ragvla",
"der ?",
"Aaj ratri nighal me",
"Aahe ka ol???",
"Kadhi ragavlo re",
"tu mala ragvto",
"katti",
"kaati",
"Kashacha re",
"?",
"mg kay karu",
"Aaj",
"Ekadashi aahe",
"Gm",
"gm",
"Zop",
"Bar",
"gn",
"me zopte",
"J1 zala",
"gn",
"ahes ka?",
"You missed a call from Rupal.",
"Rupal called you.",
"Kar",
"call karu ?",
"Nahiye",
"ata ?",
"Nahiye",
"ahes ka ol ?",
"Ek divas ithach Raha nanded la",
"So tu 29 sakali yaychya jagi 28 chya sakali ye",
"Mhanje Tula 28 chya ratri kutha rahaychi garaj nahi",
"Tar aapn 29 sakali jau",
"Me mhanlo rupal yenare",
"Abe aaie mhantiye ki 28 la ratri jau",
"You missed a call from Rupal.",
"gm",
"ok",
"Rahul yet aahe ghyayla",
"Pohonchlo nanded la",
"gnsd",
"Bye GN SD TC",
"ð",
"Are re",
"baher ahe sali",
"Roomie??",
"gnsd",
"Bye gn",
"ekat bor hte",
"Okkay",
"ho",
"??",
"me zopte ata",
"Zop aali ka",
"ok",
"Serial",
"Bar tu Bagh na",
"Me biscuits anle",
"1 epi",
"Got",
"jevla ka ?",
"Zali ka",
"band karat ahe ata",
"gn",
"Rupal called you.",
"Call cut zala",
"Aahe ki",
"range geli vatate tuzi",
"You missed a call from Rupal.",
"Rupal called you.",
"thamb baghte",
"Bamne sarvya niraj distay",
"Be",
"Bamne kunachya lagnala geliye ve",
"Rupal called you.",
"hi",
"Hii",
"msg kr",
"me got baghun zopte",
"You called Rupal.",
"Rupal called you.",
"Sorry",
"Ohh",
"bhande dhut hoti",
"ð",
"Uchalala nahi tu",
"Call kelela",
"Hoo",
"pohchla ka ?",
"Ho",
"Rupal called you.",
"pohchla ki msg kar",
"https://docs.google.com/spreadsheets/d/1WYvYf-AAmISDC3jTVYzrg2q3uf53CRM_Y7GVSd5EzK4/edit#gid=1408837171",
"The video chat ended.",
"You missed a video chat with Rupal.",
"You missed a video chat with Rupal.",
"The video chat ended.",
"Kay zalay tula",
"Mobile charge kar be",
"Rupal missed a video chat with you.",
"The video chat ended.",
"Rupal missed a video chat with you.",
"The video chat ended.",
"Ho",
"Tuza net prob asel",
"He pan nahi jat",
"Aala ka",
"Bola",
"Msg nahi jat mhanala ?",
"Rupal called you.",
"You missed a video chat with Rupal.",
"You missed a video chat with Rupal.",
"https://www.youtube.com/watch?v=-0XiiT5dR_Q",
"Rupal missed a call from you.",
"The video chat ended.",
"The video chat ended.",
"The video chat ended.",
"You missed a call from Rupal.",
"Rupal called you.",
"Okkay",
"Pn I just wanted to tell u my opinion",
"In d end tula je kraych tech krnar",
"But I still oppose",
"I don't wanna be a bad gf",
"But I don't want u to go without me with girls overnight",
"I want u to go",
"Rupal called you.",
"You called Rupal.",
"You called Rupal.",
"Can v talk for last time?",
"Me offline jatoy",
"Gn",
"Okay",
"Ani maza wait nako karu..move on whenever u get chance.. most probably I will go with sacrificing for others.",
"I know",
"Yah",
"I always loved u Rohit..n I will be wishing good for u even if v separate. I just want u to know that.",
"Gn",
"Anyways bye gn",
"I think u r better without me",
"Ani nehmi kuni bhandan pn nahi krnar",
"Maza tras nahi honar",
"Tu 2-4 months toparyant chan majja kr",
"Fine take ur time",
"Okay",
"I need a break now",
"Jamal tr kunasobthi lagn krun takel nahi Jamal tr parat try karel",
"Me 2-4 months tuzyashivay rahaych try karel",
"Mala vel pahije",
"Sadhya nako",
"Aata bye gn",
"Rahanyacha problem nahi",
"So tu ikde ye",
"Tumchya ithe rahala tras hoto be",
"Nako",
"Me yeu ka",
"Pn sadhya mala ektich rahaych aahe",
"Doghach Karu. Celebrate",
"Kahi divs de hoel me normal",
"Tyat Kay guilty",
"Tu ja yar nahitr ajun mala ayushyabhar guilty feel krvnar",
"Me pan nahi jat tyanchyat",
"Vatla tar aapn doghach Karu celebrate",
"Sadhya mala bolaychi kiva bhetaychi bilkul icha nahiye",
"Kahi problem nahi",
"31 st la ye",
"Pn",
"Tuzi kahich chuk nahiye",
"I was very excited about all plan na but it turns out like this tr sagal turn off zal yar",
"Sang",
"Ek khari gosht sangu ?",
"Chatting nako",
"Solution pn same asel",
"Call Karu ka",
"Saglyanche probs same astat na",
"Okaay",
"Pn lifestyle chng krnar nahi",
"Tu mala sodun geli tr dusri shodhel",
"Pn",
"Me tuzach ahe ani tuzyavr khup prem krto",
"Mg",
"Ek manus phone vr bolat hota",
"Me rastyane yet hote",
"Tyamulech tharav mhantoy decision",
"Ho",
"Nd v r not even happy",
"D fact is v wanna b with each other bt v r too diff to adjust with each other",
"U take decision based on facts",
"Then what do u expect from me ?",
"I don't want u to say yes to him",
"So ?",
"No",
"Does it means u want me to say yes to him ?",
"No",
"?",
"Is there anything u wanna say",
"Day after tomorrow I m meeting Gaurav's family",
"?",
"One last thing",
"Wait",
"Gn",
"Yo",
"Bye tc",
"Hv fun",
"Hv a nice time sweetie",
"Nice",
"Chalel",
"Okay",
"I asked u something dear",
"Bol",
"Rohit",
"Is that ok with u ?",
"Things will happen automatically if they r meant to be",
"Nd also there's no need to meet each month",
"So u don't need to call me everyday",
"We'll take a break nd think about all d things ur dad said",
"Kar v4",
"Okay",
"About my life",
"Kay thinkaychay",
"N I need some time to think",
"Bye",
"Gn",
"Bye",
"Then gn",
"U can skip if u r tired",
"Okay",
"Sweetie it's not a rule to talk with me everyday",
"ð",
"Kay tu pn",
"5 mintach me zopli asti na",
"Gn",
"Gn",
"Ok",
"Kasa krto",
"Huhh",
"Maza aant ka pahaychay tula",
"I m not ur baby sweetheart",
"Zopi jaa",
"No baby",
"Show me ur creativeness",
"Mg ata tyachi gosht banav",
"Aash bolat hoto",
"Gosht navti",
"Khup boring ahe me lgech zopel",
"Ata gosht complete kr na",
"Abe fakt 7hrs ahe",
"Baghu",
"Monday ofc",
"Pn return chya veles direct ikde yeil",
"Mast",
"Me Wednesday la yete",
"ð",
"Bol mag",
"Bolat bolat zopal tr mala chan zop lagte",
"Zopi jaa na",
"Rojch Kay natak aahe he",
"Rupal",
"Story sang",
"Me zopte",
"Kay zala",
"Rupal missed a call from you.",
"Rupal called you.",
"Gn",
"Ha",
"Bakichi Kahani udya",
"Gn",
"Okk",
"Gn",
"Zop yete mala",
"Mag kutra pan married life madhe vyast hoye",
"Thamb be",
"Me zopu",
"Mag yacha upay mhanun shetkari ek kutri palate",
"Roj veglya kutri chya mage firte",
"Te kutra tar farch chivari nighte",
"Boring",
"Kahi majja nahiye",
"Mothi majja tar aata aahe",
"Bakichi udya",
"Zop aali",
"Tyane 1 kutra palala",
"Nako sangu",
"Mag Kay karav ya v4rat",
"Rohit",
"Pan hybrid chi jwari tar sagle pakshi yeun khau lagle",
"Hmm",
"Mhnje ki Chara kami padu naye",
"Mhanun mag shetkaryane shetat hybrid perla",
"Karan gadhav ani ghoda doghana share karav lagat hota",
"Jaude bor hotay",
"GhodyaLa Chara kami padu lagla",
"Mg",
"Ghoda vikat anla",
"Ek divas shetkaryane",
"Ani gadhav baghun hasaycha",
"Acha",
"Reply nahi aala tr samj zopli",
"Pan bail roj Kam karaycha",
"Mag bailacha Kam pahun hasaycha",
"Mg",
"Ek gadhav hota ani ek bail hota",
"Mala ekhadi story sang",
"Humans",
"Serial",
"Tu kay krtoy",
"Bar",
"Mala nako sangu",
"Bagh tuza tu",
"Acha",
"1 bedvr 2 zopta yete aramat pn touch karan allowed asel trch",
"Sangto na me",
"Jaa gadi gheun",
"ð",
"Tyat kay",
"1 bedvr 2 ahe",
"Not possible today",
"2 bedvr 3 congested hote",
"Ani zop",
"Mag gadi gheun hall madhe jaa",
"Abe",
"I need more space",
"Ani ata mala congested vatat ahe",
"Tine mala khali zop nahi dila",
"Serial Bagh ekhada",
"Acha",
"Zop lagat nahiye",
"Kay zala",
"U must be very happy today..v talked for only 5 mins ani me bhandan pn nahi kel",
"U der ?",
"Okay",
"This is obviously not a good night. It's a life turning n horrible night. But it's good for you.",
"Bye",
"Gn",
"Bye",
"U r free now",
"So I hv to say I can't love u anymore when u broke my heart",
"I said I love you when I felt it",
"Bye",
"Gn",
"Don't worry I m not going to tell anything to anybody",
"Plz stop it",
"Rupal",
"That permission was base on assumption that u will stand by my side forever",
"But u will not understand",
"Rather than complaining about it",
"So we should leave some thing of partner",
"Which is with both of our permission",
"Anyways",
"U should hv thought before getting close",
"We are in relationship",
"I am not yet your husband",
"No",
"If expecting a loving caring husband is too much then ya I m wrong",
"But  why u r the one who is complaining",
"We both have issues",
"But I am not complaining",
"Is different than urs",
"The way I want our relationship",
"No",
"Just think clearly",
"N u r d one who is causing problems",
"Nd u r saying I am the bad one",
"U r the one having problems",
"Don't speak shit about me",
"Shut the hell up",
"I'll hate u till my last breath",
"After this break up, I won't be able to love you",
"Okay",
"U choose to let me go",
"Mg nantar mhanayla nako I didn't gave u chance to stop me mhanun",
"N that's y asked u",
"U r the one with problems",
"So v r done ?",
"No",
"Do u hv something to say",
"Ho",
"I asked u something",
"Hm",
"Tevha pn chance nahi milnar",
"For next 2 years u will b with ur frnds n colleagues",
"To call",
"Didn't got any chance",
"With family and friends",
"Nd bdw I was in village",
"R*",
"So u responsible person",
"So what",
"Friends",
"U were with",
"I was out till 3 then I was at in mountain for whole night with all drunk boyz.. anything could happen..u didn't bothered at all",
"?",
"Kashavarun vatla tula",
"Asa",
"Okay",
"Me asli kiva nsli tari tula kahi farak padat nahi",
"Te sang",
"Mazyat Kay problem aahe",
"Tula",
"Or else v r done here",
"I hv only 3 days left..if u want to say something, say it now.",
"Bol",
"You missed a call from Rupal.",
"You missed a call from Rupal.",
"Rupal called you.",
"Rupal called you.",
"Rupal called you.",
"Bol",
"You missed a call from Rupal.",
"Ok",
"I figured out that already",
"Pohonchlo room vr",
"Hasu nako",
"ð",
"ð",
"Asa aahe ka",
"Acha",
"Bye",
"N I just can't do this anymore",
"I m disappointed",
"Me ragat nahiye",
"Nd u don't love me",
"I know u more than u know urself",
"Compromises adjustment krnyat mala kdhich prob nvta but this is diff",
"Space saglyana havi aste Rohit pn now I started to feel like u don't care at all",
"Tula farak nahi padat kshacha",
"?",
"Then",
"It's not about that",
"Asakahiyri mhanalohoto",
"Phone thev",
"Kay mhanala hota tu kal ?",
"Yesterday",
"I was just kidding",
"So bye",
"I seriously don't wanna talk to you again..I m suppose to feel good with u but I feel horrible about how u treat me..I m done.",
"Okay",
"Bye",
"Blur ka aahe itka",
"Tuza profile pic baghitla aata",
"Nako karu",
"I don't wanna talk to you",
"Train mafhe baslyavr karto call",
"Abe me ghari aahe",
"Rohit",
"Gn",
"Okay",
"Bye",
"Ok",
"Tu ignore karat rahila tr mala vatel u want me to marry him",
"Plz",
"But don't ask me questions now",
"Then decide",
"I hv to decide yar",
"Sobbye",
"I can't take it now",
"We talked about it more than enough today",
"Zop aata",
"Aaik",
"Tu mazya jagi asta tr kay kel asat..",
"Kay aata",
"ðð»",
"Rupal called you.",
"Gn baby",
"Hi",
"ðð»",
"Rupal called you.",
"Ajun nahi..me tp sathi mulga shodhat ahe",
"Tc",
"Zop gn",
"Okk",
"Ho",
"?",
"Zopi ka",
"ð",
"Ek mahina kay ek divs pn nahi zala",
"Our relationship is screwed",
"I don't love u",
"Not chatting to u doesn't mean that",
"Tu Zopi jaa ani mala pan zopaychay",
"It's so hard...apan nahi rahu shakat bhandlya shivay",
"So plz",
"We r two ends",
"Banvu pahatiye",
"So ka tu mala tuzya mana sarkha",
"Me pan mazya jagi Barobar aahe",
"But",
"Tuzya jagi",
"Tuza Barobar aahe",
"Me kay karu yar... mala bor hote",
"Mag ka v4 ti",
"Ki me Tula wholeheartedly permission nahi denar",
"Tula pan mahitiye",
"Mag ka mala ragat ananyasarkhe que v4ti",
"Ho",
"Tula mahitiye na me chidchid karto",
"Kay",
"Why",
"Baby",
"Rohit",
"K",
"Hm",
"U r failed in romance dept",
"Bye",
"Gnn",
"Okaay",
"Tu zop",
"Tula nahi kalnar",
"Okkay",
"Mala ratri bolaychi savay hoti..itkya easily kashi janar",
"Just appreciating u",
"No taunt",
"Taunt maraychi garaj nahiye",
"Hats off to u",
"Tari aajun bolayaychay",
"Company keli",
"Kela",
"100 km divas Bhar pravas",
"Sakali 7 la uthaliye",
"Yar tu kashi vyakti aahe",
"Asto kadhi kadhii",
"Kadhi asto",
"So gn",
"Aaik me TP karnyachya mood madhe nahiye",
"Okay",
"I kissed someone",
"Hat yar",
"Nahi",
"Is there any way to go in coma for 3 years",
"Rohit",
"Thoda vel",
"Dole mit",
"Aapoap lagte",
"Body pain",
"Zop lagat nahiye",
"Bol",
"Bye",
"Ata gn",
"Gn",
"Cool",
"Ho",
"After ur family trip ?",
"Nantar baghu",
"Jaude aata",
"Mazya flat vr nahi be",
"Nahi mhanali tu",
"Aalo hoto tenva",
"ð",
"Try to understand my needs baby..I m 22",
"Tc",
"Gn for now",
"Kadhi",
"Nantr",
"Baghu",
"Aapan kadhi bhetu",
"Bar",
"It's been a long time",
"I want do it with u",
"Bdw",
"Kahi pn",
"Kay sangu ? Ur bs r touching",
"Ki thoda mage basat jaa",
"Mag sangun tak",
"I feel awkward",
"I can feel her bs..itkya javal",
"But mazi ek frnd na gadivr khupch javal bste..",
"I m not interested in girls",
"I feel weird yar",
"You called Rupal.",
"You missed a call from Rupal.",
"You called Rupal.",
"Rupal called you.",
"You missed a call from Rupal.",
"You missed a call from Rupal.",
"The video chat ended.",
"You missed a video chat with Rupal.",
"Hey",
"Bye",
"Bye",
"Ohhh no",
"ð",
"Muli nastat",
"Bye",
"K",
"ð",
"Swimming pool vr hirval hoti ka",
"Bye",
"Aata nightoy ofc la",
"Mast",
"Zzali",
"How was ur swimming",
"So",
"ð",
"ð",
"Ok",
"It's just a coincidence",
"Nd bdw me stalk karat nvti",
"Morning",
"Gm",
"Gn",
"Gn",
"It's fine",
"So no need to talk to me everyday..",
"I was just testing today..nd u did quite good.",
"Nd I realized God didn't made any ideal man for me..mg compromise kraychch ahe tr tuzyat kay prob ahe.",
"The image I sent was my dp.",
"I don't want multiple physical relationships.",
"It's bcoz I love u nd more importantly I m willing to do anything for my character.",
"N I hv decided to compromise everything..just like I'll do in case of arrange marraige.",
"ð",
"Senti msg nako mhanala hota",
"ð",
"No msg mhanalo hoto",
"Gnsd",
"ð",
"Bye",
"Udya bolu",
"Gn",
"Rupal called you.",
"So think to tackle the situation",
"But this relationship is not working out",
"Be practical",
"Itka motha issue nako banvu",
"Bye",
"Take care sweetheart",
"I love you",
"Keep updating ur fb status coz I can't call u like sheetal does..u know my moral's r different.",
###############################################################################################################################################################################################################################################################
"Bye tc",
"Don't forget that this crazy person loves u a lot n always will",
"Rohit",
"Ya I also forgot to eat today..ani ata mood pn nahiye..I easily catch fever when I start cry...u r right I m not healthy too",
"I should die alone",
"Person like me don't deserve love",
"I will not ruin ur life again",
"This is fucking crazy...I can't make man happy",
"Maybe I m not made for  relationship thing",
"He tried so many times but I never responded",
"Maybe agodr pn mazach fault asel",
"This is all my fault",
"I can't work out any relationship",
"N my life is so pathetic",
"This is so unreal",
"Bye",
"It's 10:45 Nd I haven't eaten a single thing",
"Nd we will see",
"Live  single life",
"So take a break",
"Becoz long distance is not working out",
"Ho",
"ðð»",
"ðð»",
"But do u think that is d best option ?",
"Wait kr mhanala tr nehmi wait krtch rahil",
"Prem ekdach hote Rohit..ani maz prem tuzyavr ahe",
"U r d best man in the world for me",
"When I say I love u",
"Better bhetlyavr mulga chng krnari mulgi havi hoti tr Shraddha sobt continue krayla pahije hota",
"And then decide",
"I m not going anywhere",
"So take your time",
"And I can't ignore your concerns about long distance for 3years",
"Becoz long distance is not working anymore",
"Nahich avadla tar vat bagh",
"Tu tyachyasobat lagn kar",
"Mazyapeksha changla aasel tar",
"Jar ya 3 varshat Tula Kuni dusra avdla",
"Me mazya life madhe vyast hoto tu tuzya houn ja",
"Lets break up for 3 years",
"I got a solution in this regards",
"You called Rupal.",
"You missed a call from Rupal.",
"You missed a call from Rupal.",
"Rupal called you.",
"Rupal called you.",
"You called Rupal.",
"Rupal called you.",
"Headphone",
"Rupal called you.",
"Rupal called you.",
"Rupal called you.",
"The video chat ended.",
"You called Rupal.",
"You missed a call from Rupal.",
"Rupal stopped viewing your video.",
"You started sharing video.",
"Ho",
"Ali ka",
"Rohit ek request ahe..atach bhandan zalay so tula advantages athvnar nahi..agodr thoda changla time athv ani photos paha mg start kr.",
"Rupal called you.",
"Okk",
"Ani mg sagle mala yeun sangtat yar",
"Okk",
"Amche comn frnds",
"Konte frnds",
"Ti saglyanach business kr mhnte",
"Ani back bitching karat ahet",
"Sagle frnds tichyapasun dur hot ahet",
"?",
"Kaskay",
"ð",
"Abe I feel sad for Shivani",
"I m proud of u",
"Ho",
"ð",
"U should be proud of me",
"ð",
"ð",
"Me tari nahi sangital",
"Te mul mg mhanat hote k at least evdh sangayla sang ki amchyat better kon diste",
"ð",
"Acha",
"ð",
"Pn me hi kelch nahi",
"At least Hi tari",
"Intro ch krun de mhanat hote",
"To mrun cha Japanese wala grup tr ekdam flat zala hota",
"Ani",
"Kal khup mul line marat hote",
"Acha",
"Are pic tevdhe chan nahiye pn",
"Pic pathav",
"Wow",
"Kal me khupch chan disat hoti",
"Gm",
"Gm",
"Kay zala",
"Wait",
"Bye",
"Gnsd",
"I love you",
"Apan fakt ekch karat rahto",
"Mala ashya saglya goshti tuzyasobt kraych ahe",
"Kay",
"Rohit",
"Gn",
"Gn",
"Bye",
"Zoptoy me aata bye",
"Okk",
"1 time",
"So nahi gelo",
"Kasa aahe aamhi janar hoto pan Rahul chi exam aahe Monday pasun",
"Fantastic beasts",
"Konta mve",
"Ani 1st time itkya ratri gadi chalvli",
"Me 1st time night show pahila",
"Movie bghitla",
"Okk",
"Hinjewadi",
"Frnds sobt geli hoti",
"ððð",
"?",
"Bdw kuthe geli hoti",
"Zopte ata",
"U r really cool",
"Me tr 50 vicharle aste",
"Me 2 vajta aali nd u didn't even asked a single que",
"I felt that u r very cool",
"Ani",
"Acha",
"Itka divas tikte",
"Nahi athvat pan ghalun ghalun bore hote",
"2 varsha kharab nahi zali",
"Kitila ghetli hoti ?",
"mazyakade jocky chi hoti chaddi",
"Acha",
"Ho",
"Changal aste ka ?",
"Ho",
"Jockey brand aikal ahe ka tu kadhi ?",
"Tyanach mahit aste",
"Mulina v4",
"Mg ks karu ata",
"Abe",
"Mala nahi mahit",
"Kharch evdhi mahag aste ka ?",
"Pori mhanat hotya tevdhyalach yete",
"Acha",
"Me na ek B pahila.. comfortable hoti chan..pn to 800 mhanala mg nahi ghetli",
"Bol",
"Aik na",
"Gnn",
"ðð»",
"Der ?",
"ðð»",
"Gn",
"Ok",
"Tu zop",
"Thoda vel",
"Fb baghtoy",
"Kahi bolaych ahe ki zopto ?",
"Acha",
"Tr ol disla",
"Tuze kahi call msgs ahet ka baghat hoti",
"Me atach ali",
"Haa",
"Chaan",
"Are wah",
"Zop lagat asel khup tr zop",
"Kahi nahi dinner la gelo aaie baba Rahul Nd me",
"Kay kel aaj ?",
"Acha",
"Ani aata ol aalo msgs baghitle",
"Itka vel serial baghitla",
"Acha",
"Zopaylach jat hoto",
"Zopla nahi ajun ?",
"Ho",
"Der ?",
"Gn",
"Zopla ?",
"Bye",
"Bye",
"Ho",
"Ok",
"Did mahina aahe",
"Tharavu kahi tari",
"Bar",
"I genuinely wanted to be with u on 31st...next year nahi rahu shaknar na.",
"Bola ki",
"ðð»",
"Rohit",
"Baghu",
"Acha",
"Nahi mahit Visakhapatnam la pan jau shaktat",
"Mala mahit ahe tumcha grup Goa jael fakt",
"Wait",
"What about ladakh ?",
"Ani Kerala tr family trip pn jate",
"Bar thik aahe",
"Trekking krayla jatat frnds",
"Tula tech disat be..place vr kahi honeymoon sathich ahe asa lihil nste",
"ð",
"Pagal aahe tu",
"Abe trekking place ahe",
"Abe tu parat ek honeymoon place kadhla",
"Tula suggestions vichartil tr Manali Sang",
"Ok",
"Mag aapn jau",
"Ani tumch cancel zal tr ?",
"Nahi awkward kahi",
"Tu awkward nahi vatnar ?",
"Tenva tu pan add ho",
"Nahi tar aasa Karu amche hyderabad wale may be Jan madhe karnar aahet plan",
"Jaycha aahe mhanunch boltoy na",
"Mg me search karel",
"Seriously jaych ahe ka ?",
"Acha",
"Parat nahi jaych",
"Me jaun aliye tithe",
"Just kidding",
"Hm",
"ð",
"Mandirat",
"Haridvar chal mg",
"Baghu",
"Dusar sang mg frnds wala place",
"Mag aikun Kay aahe te",
"Mala nahi mahit",
"Te honeymoon place ahe ka ?",
"Abe honeymoon places ka choose kartiye",
"Place decide zalyavr pudhch bghta yet",
"Tu sang Manali ki Kerala",
"Tharav mhanat hoto",
"Kal kay mhanat hota trip ch",
"Ghari thand basun rahaycha",
"Kahich nahi",
"Kay program ahe mg aaj?",
"Acha",
"Sakali 7 la",
"Kevha pohchla ?",
"Chalte",
"ð",
"Ofc mdhe photo allowed nsto",
"Hat*",
"Hay shake hotat re gym kelyavr",
"U need DSLR",
"Blur ahe",
"?",
"Thik aahe na",
"Baghitla",
"Ho",
"Dp baghitla ka wa cha",
"Ohh",
"Nothin",
"Ssup",
"Hi",
"Hi",
"Ok",
"Gn",
"Gn",
"Gn",
"Mala zop nahi lagnar",
"Aata ugi Senti msgs plz nako karu",
"Mazyat nahiye",
"Gn",
"Tuzyat aahe capacity sakali lavkar uthnyachi",
"Gn mhan ani Zopi jaau de mala",
"Gn",
"Bye",
"Tu te tension free karnyasathi asavi ki vadhavnyasathi",
"Bye",
"Ok",
"Me kahi natak karat nahiye yar",
"Ja udat adhich dokyala khup tension aahet",
"Movie samplyavr call kela tar tuze nataka suru",
"Thamb",
"Mhanun mhan alo thb",
"J1 Karun movie baghat hoto",
"Ratri gym Varun ghari aalo tenva call kela",
"Sala divas Bhar chatting kela",
"Kay vel nahi mhanti be tu",
"Gn",
"Bye",
"I m sick of u.. tuzyakade saglya sathi vel ahe. Except me. Sodu pn shakat nahi ani rahu pn shakat nahi. I hate this condition",
"Plz gn mhan Na yar",
"Udya parat 9 la bolavlay ofc la",
"Don't have energy to think on it",
"I asked something",
"Gn",
"Itkach bolnar hoto",
"Ki me zopi jatoy bye",
"Bol",
"Phone karnar hoto",
"Kay bolto te re",
"Kay aikun ghe ?",
"Aata Kay zala",
"Bola ki",
"Gn",
"Bye",
"Ani me zoptoy",
"With mobile network",
"I thought text msg",
"Ata msg ch kela n",
"Fakt aikun ghe",
"Msg pack nahiye",
"Msg kasa karu",
"Abe",
"Tc",
"Bbye",
"Gn",
"Gn",
"Ok",
"Shant ho",
"So plz",
"Me kahi itkya pan tokala jaa mhanav nahiye",
"Direct bhetlyavrch bolat jau mhanje ugich mazyamule tula roj disturb nahi honar",
"Kami bolala tari chalel",
"Tasa samjaycha tar samj",
"Me kahi kunasobt affair krnar nahiye",
"Plz kraych ka tas ?",
"Ata 5 min bolala tari tu mazyavr upkar krtoy asa vatat mala.",
"Tu agodr pasun asa nahiye yar..me phone bill bharalay..I know 1-2 tas bolat bsaycha..ani tula kalaych pn nahi itka vel zala.",
"Aapan kharach tas tharvu na ki fakt bhetlyavr sobt..baki vel no contact.",
"Rohit ekch min plz",
"You called Rupal.",
"Clearly sang",
"Ambiguous reply ahe tuza",
".gn",
"Bar",
"Obviously no flirting",
"Nd sometimes I really need to talk to somebody.. specifically boy..nd tuza kadhich mood nsto..u hv to give me permission to talk to other boys",
"Baghaych ahe drinks mdhe evdh kay enjoy krnya sarkh ahe",
"Maybe tuzi lifestyle samju shakel yamule",
"3 boys 4 girls ahst",
"Pn ata jaych tharval",
"Previously I said No",
"Ya weekend la frnds cha club mdhe jaycha prog ahe",
"Ani ho",
"Bye",
"Enjoy urself",
"Tu vinanti krshil na tevha pn nahi bolnar.",
"Ata na callch nahi krnar..",
"ð",
"Thanks",
"I hate u",
"Rupal called you.",
"http://m.economictimes.com/nri/visa-and-immigration/donald-trump-favours-indian-students-staying-back-in-us/articleshow/51407129.cms",
"ðð»",
"I m taking a break",
"Tula kalat nahi mhanun clearly sangat ahe",
"I seriously don't like u",
"Me nehmi tya colg chya Rohit vrch prem kelay..jo garaj nstanahi mala sagal sangaych..maz opinion ghyaycha ani aikaycha pn..jo nehmi mazyasathi vel kadhaycha",
"Gn",
"Me zoptoy",
"Okay",
"It doesn't matter",
"Sorry ch kay karu",
"Maza tuzyasarkha planned naste",
"Sorry mhantoy na",
"Mala nahi avdat asa Rohit",
"Aata zoptoy me",
"Personality",
"Acha",
"I was talking about nature",
"ð",
"Me open tu obc",
"Okk sorry for that",
"That's bcoz apan veglya category che ahot",
"Tu te kahi krto te sagalch unknowingly krto ani te disappointing aste",
"Please don't think as I knowingly didn't tell u",
"Sagal aplya manavr depend krte",
"Whatever it maybe",
"Ain time vr tickets kadhle",
"Mich stupid ahe",
"Me pn nahi sangat janar ata tula sag",
"Tu sangital pn nahi",
"Acha",
"Dr strange",
"Name ?",
"3d effects were awesome",
"Konti ?",
"Mast ekdum",
"Kashi hoti movie ?",
"I know",
"Was kidding",
"Okay",
"This is not funny",
"Rohit",
"Bbye",
"Jaato me aikayla",
"Me pan nahi karat aahe",
"Me joke karat nvti",
"ð",
"Bajuchya building madhe",
"Kunitari khup mast gana mhantay",
"Nako",
"Chal me zoptoy gn",
"ð",
"Ok",
"Kalel kskay avaj kuthun yetoy",
"Mag jaun mhan Na parat vajav",
"ð",
"Avaj band zala tuzya nadat",
"Kay",
"Ek min",
"Gn",
"Ho",
"Tu zopto?",
"Yo",
"Jaa mag",
"It's safe",
"Vrch tr ahe",
"Secure nahiye",
"Why",
"Then don't go",
"Baki sagle Zople be",
"Okk ekti nako jau",
"Maybe vrchya flat vrcha mulga vajvat ahe",
"I really like it",
"It's guitar baby",
"Ka jaycha pan",
"Bye gn mhanshil tr mala net off krun jata yeil",
"Kay mhanu me aata",
"I m loving it",
"Mast vajvat ahe",
"Mahit nahi... kuthetari guitar cha avaj yet ahe tithe",
"Kuthe",
"Gn",
"Bolu nantar",
"Me jat ahe baher",
"Bar",
"ð",
"Ohhh",
"Sanhitla fakt",
"Nachu ?",
"Mg kay karu ?",
"Acha",
"Ghari be",
"Kuthe aalo ?",
"Aalo*",
"Kay",
"Also aata",
"There ?",
"Magav",
"Black wala sangu na ?",
"Return nhi hot",
"Ho",
"Sure ?",
"Tula large lagel",
"I m confused",
"Ki mala konti size hoel",
"Ani mala sanh",
"Check kr",
"https://docs.google.com/forms/d/e/1FAIpQLScYb-87vczM28q71vQtSRgzJGnjke0-TwmdbO1O1sNQbNKkCg/viewform?c=0&w=1",
"Bye",
"Good day",
"Bye",
"Nantr bolu",
"J1 bnvaych ahe ata mala",
"You missed a call from Rupal.",
"Gn",
"Range geli hoti",
"Bye gn",
"Chal zop aata",
"I don't want to share u",
"Ka",
"Nahi",
"Bol na",
"2 boys 2 girls ka nahi ?",
"Ho",
"Nd u can hv other 3-4 girls to do it with u some another time when I m not around",
"Then no need",
"2 boys 2 girls",
"I didn't mean that",
"3girls and me",
"Yah sure",
"Can v hv foursome instead of 3",
"Acha",
"Not at all",
"In physical way",
"Do u like boys ?",
"Ohh",
"Abe lagn aahe aaichya mavas bhavachya mulacha",
"Mhanun",
"Tu kay bolto",
"Me kay vicharte",
"?",
"Kaskay",
"Nahi",
"Dokyavr pdla ka",
"Is a question cum expression",
"Kunachya lagnach ?",
"What the fuck",
"Wtf",
"Wh type",
"What type",
"It is an interrogation verb",
"?",
"What",
"Lagnacha bolayla",
"?",
"Kaka kaku kskay yenar aahet",
"ð",
"ð",
"Funny nvta",
"Kahitari tu",
"Bol kahitari tu",
"Hope so",
"Nahi",
"Better milalyavr mala sodshil ka manu ?",
"Nice thoughts",
"Acha",
"I m worried",
"Mg tu cheat karnyache thode chances astil",
"ð",
"Pn tu US gelyavr tithlya muli mazyapeksha better astil",
"Who told u that",
"But v both know that I m better than all those girls",
"Tu kontyach mulina bhav det nahi ata",
"Konta",
"Bdw Ek v4 mala khup disturb karat ahe",
"Mg mala vatel I m not enough for u",
"Acha",
"But I still don't like sharing",
"Threesome",
"Kskay ?",
"Mazyakarta changla aahe",
"Who likes both ?",
"M I turning into multisexual personality ?",
"ð®",
"Means u liked it",
"Acha",
"But d weird thing is I noticed it",
"I m not saying I didn't liked it",
"ð",
"Coz u r a boy",
"I would have liked it",
"Mag Kay hota",
"It was weird",
"I felt her b***s touching my body",
"?",
"But d embarrassing thing is",
"Ti purn mazyavr wait takun bsli hoti",
"So",
"Ani tila bar vatat navat",
"Mag",
"Ti mage bsli hoti",
"Me eka frnd sobt geli hoti double seat",
"Bol",
"Aaj kay zal",
"Acha aik",
"Abe range nhi h na",
"Kk",
"Abe free to aahe na",
"Msg send hot nahiye",
"Abe WhatsApp la jast data lagto",
"10 km",
"Sobt running karu",
"Ani 20 la yaych asel tr tu pn marathon mdhe participate kr",
"Gn",
"gn",
"Zop ata",
"gaurav sobat tuzi family",
"neeraj sobat tu boltiye",
"there is difference",
"Ugich disgusting vagere nako",
"Me kahich nahi kela be ts",
"Neeraj fakt frnd ahe tr tula rag yeto...pn Gaurav sobt lagnach suru asunhi tyach kahich nahi vatat tula",
"literally it is very disgusting",
"plzz nako karat jau aasa",
"Ek gosht sang",
"ki jealous karnya cha",
"Nahi be",
"tu mala ragat ananyacha prayatn karti ka",
"zalay",
"aata paryant 2 da 3 da",
"Pn asta tari grup mdhe geli asti",
"tras hote na fukatcha",
"ka mhanti yar",
"Velch nahiye",
"Abe ekti thodich geli asti",
"ugi 40 min zale bhandan kartoy tya eka vakyamule",
"doka nahi ka sarknar",
"mag tu mhanali neeraj sobat jatiy firayla",
"tyamulech tar space deto yar",
"Aajch ek try marat hota pn me ignore kela na samjlyavr",
"i dont care tu kunasobathi firtyr",
"Me kuthe bolte yar mulana",
"me tula space dili yacha artha asa nahi ki",
"me asa bolto ka yar mulinsobat",
"Ho mahitiye mala",
"neeraj nahiye changla rupal",
"Mala kdhich nvta kraych nee sobt..v4 pn nahi krnar",
"majak madhe mhanalo hoto",
"Tu tichyasobt sex kraycha hota",
"mala nahi kalat",
"bdw te yetach kuthun yar tuzya life madhe",
"Shraddha ani to kahi same nahiye",
"jar agree asashil tar bol",
"je tu tyachya sobat karshil te me shraddha sobat karel",
"Ani barach kahi",
"Gadi servicing ahe",
"tu tyala as shradha samj for me",
"Agreement kraych ahe",
"Nahi jat ahe yar..vel nahiye mala",
"ani varun tu tyala mazya frnds sobat compare karti",
"wow great",
"but tula tar tya neeraj sobat jaychay",
"Tikvaych nahiye mhanun itka vel det ahe ka",
"so plz mazyavr khapar nako phodu",
"me nahi",
"tuch he ques chalu kelet",
"nd asked u about that as well",
"Khup tension ahe agodrch mala",
"yah i know that",
"Maza bhau 7 divsapasun aajari ahe..admit ahe bichara..j1 jat nahiye ani ajun khup kahi",
"saral sarl sangun mokli ho na",
"Aik ata",
"jar tula tikvaycha nasel tar",
"me ugich mahenat kaa karu",
"important aahe",
"Tu swatala v4",
"I m not answering that que",
"Mala samjte sagal tuzya baddal evdhch sangaych ahe",
"?",
"tula tikvaycha ki nahi",
"Bs",
"tu aaik",
"Break up mdhe kahi prob nahiye",
"Sheetal wali pn misunderstanding nvti... jealousy mhanu shkto",
"Me muddam mhanali",
"Misunderstanding nahi kahi",
"just look at urself",
"again miss understanding",
"ani phone vr nahi bhandta yet",
"rahul aahe itha",
"Sorry for disturbance I caused",
"Ohh",
"call nako karu",
"All d best for ur future",
"Tc",
"Bye",
"Ok",
"Well d reason was she is ur 1st love nd I heard lot of romantic memories that's y",
"so thats why i m breaking up with u",
"i m not capable enough",
"i cannot handle u",
"its over my head",
"literally",
"u go ahead with ur life",
"sod na",
"genuine karan asta",
"tichyach classmates",
"13 muli aalya hotya",
"mala nasta bolavta tila?",
"khara sang",
"ani sala tu mazi ulat tapasni ghete",
"pan nahi bolavla",
"me tila GT la bolu shaklo asto",
"fakt mazyakde ticha no aahe",
"ti kunachyahi contact madhe nahiye",
"aata khup changla chance hota",
"mala jar sheetal la bhetaycha aasta tar",
"aaik aata",
"why u always compare urself with sheetal",
"what is more charishing than that",
"Ur relation with ur ex",
"we had sex together",
"r u fucking insane",
"what was there to cherish",
"i didnt talked to a single girl personally",
"I said about old memories",
"Me kevha mhanali tas",
"u r thinking that i went to show off myself",
"u dont know me at all",
"asto",
"jar me tasa aslo astotar kiti hava karun aalo aste",
"literally kunalach nahi",
"me kunalach nsahi sangitla ki me MS la jatoy",
"me mazya mitrana bhetayla gelo hoto",
"me kahi titha mulina bolayla gelo navto",
"je tuzyavr line martat",
"are i hate u talking to boys",
"muddam",
"u know i hate that guy",
"kaich garaj navti",
"me kitihi chanhgla vaglo tari tu shevti bhandan ananar",
"tu na maha chu aahes",
"bye",
"haa",
"R v breaking up ?",
"gn",
"bye",
"Nako bolu kahi",
"dont",
"Wait",
"but u dont know what happened there",
"till now i was not serious about break up",
"i will not be there to stop u",
"u do whatever u want",
"its done",
"Barobr ahe diff tr ahe",
"aaik na rupal",
"I m not doing that",
"Tumhi sheetal sarkhya junya athvni cherish karat hota",
"u  not",
"i went to meet my male friends",
"there is difference",
"Frnds sobt",
"nako jjau neeraj la bhetayla",
"Tu pn tr firun ala",
"simple",
"Kalat nahiye tu ka asa mhntoy",
"Wait",
"aani jaycha aasel tar nako bolu parat mala",
"What",
"nako jau",
"Udya neeraj yet ahe... weekend trip cha v4 suru ahe",
"u said enough",
"no need",
"nako sangu",
"Garaj nahiye ts pn tari",
"Ek sangaych rahil yar",
"gn",
"Bye",
"K",
"Kay zal",
"zop aata",
"bye",
"ð¡",
"kunihi kay",
"aye",
"Tula toys lagtat ka ?",
"Maza mood asla tr kunihi ready hoel mazyasobt krayla..toys kshala pahije",
"acha",
"Me ts kahi karat nahi",
"Hat be",
"for woman",
"sex machine",
"Mhanje kay ?",
"do u want sex doll",
"bdw",
"aahe",
"ho",
"Tu selfish ahe",
"bolti ka aata",
"ð",
"but i am all that she will get",
"she deserves far better than me",
"As a frnd ekda v4 kr rupal kay deserve krte",
"Mhanun mich sangat ahe",
"Vichar krayla tuzyakade time nahiye",
"U don't really love me",
"For ur info",
"donhi options wrong aahet",
"Me kahi vicharal na tula",
"mag",
"zop na",
"Bol yar lvkr",
"ðð»",
"Mala zopaychy",
"Ata seriously sang yar",
"Mazyapeksha changli milel tula sex sathi",
"sexx partners",
"Bol na",
"Vicharat ahe",
"Apal pudhch relation",
"kay",
"Frnds or known strangers ?",
"moti saban ananyachi vel aali",
"Tc",
"utha utha diwali aali",
"Goodbye",
"Ok",
"chala aata",
"bar",
"Nd obviously I don't want to chng u",
"It's ur nature...u don't like to share",
"This is not going to chng",
"He asch hoel yar ayushyabhar",
"In short tula velch nsto",
"Ani asla tari tu rikama rahat nahi",
"sangitla na",
"aaj nahiye ka",
"Tula vel asto",
"Nivant pn kadhi yet nahi",
"Aik",
"tula lage kalach aaikun ghyacha hota",
"Friends rahaych ki nahi ?",
"tula nivantpanat sangel na",
"nahi honar",
"Tyapeksha nako",
"Mummy Papa sarkhach hoel",
"Nahi nako",
"Pn last week mdhe khup kahi zal asnar right..me ek gosht vicharli mhanun kalali",
"I m not talking about that",
"ugi khota aal nako aanu",
"Break up karu",
"tula sangitliye sagli story",
"Jaude",
"Nahi tikvaych Rohit mala",
"See I was right..khup kahi hot n u don't even bother to share with me.",
"me tila letter madhe lihila hota ki i love u",
"U proposed her ?",
"asked me how u propossed sheetal",
"truth and dare madhe",
"chidavla",
"Last week madhe vicharal be..Ani kuni tula sheetal baddal kahi vicharal kiva chidval nahi ?",
"kai pan ka",
"ghari aahe be",
"R u sure tu drink nahi kel ?",
"work accordingly",
"nice plan",
"acha",
"ð",
"Tu maz purn aikalch nahi..madhech que vicharun topic chng kela",
"ho",
"Break up kela asta tari ala asta ?",
"asch yetoy",
"nahi tyakarta nahi",
"Sagal normal krnyasathi yaych mhanat ahes ka ?",
"Ek min",
"26-27",
"tyachya",
"next sat sun",
"Mala jaychay",
"Nako yeu..",
"Rohit 20 la marathon ahe",
"Kahi krnyasarkhi jaga nahi milnar",
"Yeun fayda nahi honar",
"fakt rahanyachi soy bagh",
"asach sahaj",
"19-20 Dec ka asa vicharat hoti",
"kay karaycha te",
"december plan karut nantr",
"udya jaun dd kadhayche ielts",
"December ?",
"topryant free hoil",
"asach",
"Kskay",
"so stay put",
"sat sun",
"i m planning pune trip may be on 19-20th",
"just go to sleep",
"then nothing else matters",
"But it's not working",
"Obviously yes Rohit",
"so just tell me yes or no",
"u r weirder",
"now a days",
"U said u know me better than myself",
"yes or no only",
"?",
"tula tikavacha ki nahi te sang",
"mala baki kahich aaikyach nahi",
"aaik",
"I m not done yet",
"tc",
"bbye",
"so i am breaking up with u",
"even i tried",
"I tried Everything",
"Nd there's nothing I can do about it",
"Tuzyasobt me jevdhi khush aste tevdhi dusrya kunasobtch nste..I feel like dream come true. Pn 2 divs anand ani mg 2 mahine radat bste..",
"proceed",
"Can I ?",
"Kahitari sangaych aahe ajun",
"sorry if u thought it in that way because of my action",
"i dont have any interest to force u",
"goodbye",
"if u r not happy with me",
"Tu khup chaan aahes Manu..ani adhun mdhun khup chaan vagto.. like today pn te bakiche divs maza jiv ghetat",
"wait",
"Rupal khup chaan ahe...tuzi khup kalji gheil.. saglyanchi respect karel..etc etc sagal manya ahe pn ti swata khush nahiye hi gosht kunala lakshat pn yenar nahi",
"no suggestions at all",
"Any suggestion ?",
"Anyways this is not d way how I want to live my life",
"okay",
"Tu 1 tari deu shkto ?",
"I can give u 10 examples for that",
"tula watate",
"kahi",
"khup space nahiye",
"aaik",
"Khup space milali tari prob ahe ani kahich nvti tari prob hota",
"Mhanun ajun sobt ahot",
"Ani dogh kahi vait nahiye",
"Saglyana sangitalay",
"Mala asa vatayla laglay ki",
"mag me karna apekshit aahe",
"2 min",
"M trying to tel u",
"ð",
"Maybe mazyatch kahi prob asel",
"mag mhanaychay kay tula",
"But I m not happy with this much space",
"It's actually good..v hv our own life ani vel milala ani mood asla tr ekmekana vel deto",
"ha",
"Barech divs bolalo nahi tari chalte",
"Even zalyavr nahi sangital tari tevdha kahi prob nahiye",
"We don't need to ask anything before doing anything",
"But not normal",
"In some way it's awesome",
"Apal relation khup diff ahe manya",
"bol na",
"Der?",
"ðð»",
"k",
"Hath dhuvaycha ahe",
"2 min",
"jitki garjechi aahe titki deto",
"me kahi khup jast space nahi dili",
"But",
"I said yes",
"Ti mhanali aata tu khush asnar tula khup jast space milali",
"Aplya baddal sangital Pooja la",
"Mg",
"Ani to 5-5 mintacha hishob thevaycha",
"N I said ki to mala kahich space det nahi..mala space havi hoti",
"mag",
"Sumit ani tuzya break up ch reason kay ahe",
"kay",
"Pooja mala nehmi vicharaychi",
"hm",
"1 min",
"better u mail me",
"I feel empty",
"Pros n cons chi gosht nahiye re",
"every relationship has pros nd cons",
"ha",
"R u hpy with this ?",
"ka timepass kartiye",
"sangun mokli ho ki",
"ekach laun dilay kenvhacha",
"bol na",
"I mean bolaych ki mail krun taku",
"Mala mahit nahi tuza mood sadhya kasa ahe",
"bol na baba",
"ðð»",
"Kay zal ?",
"Bbye",
"Nighalo shivpuri la",
"ðð»",
"Rohit 1 gosht aik na",
"Gn",
"Gn",
"Nahi",
"U der ?",
"Bol ani zop",
"ð",
"Tula kharach vatat me tyachyasobt lagn krav ?",
"Kay mast",
"Mag mast na",
"Ani 6 pack nahiye",
"Chaan disto pn chashma ahe",
"Baghitlay me..",
"Kasa aahe te",
"Search larnar hoto fb vr",
"2 min",
"Surname mahit asta tr kay ?",
"Udya bolu",
"Bye",
"Kasla tuza family friend",
"Jaude mag",
"Tyach nahi mahit...tyachya aaich lagna agodrch mahit ahe",
"Tula",
"Surname nahi mahit ka",
"Mala nahi mahit",
"Nav kay aahe tyach purna",
"Achaa",
"Me ajun ho nahi mhanali lagnala mg ks fix krtil",
"Ghar mast ahe..bath tub pn ahe.. superb",
"Kiti divsapasun chalu hota ki tuza",
"Nahi tuza tar lagn fix karnar hote ki ya diwali la",
"Kahi nahi bs vatal sangav mhanje tu aapla kahitari v4 krshil",
"Mag kay zala",
"Bar zal to nvta",
"Aaj Gaurav chya aajoli gelo hoto faralala",
"Bol",
"Acha aik",
"Udya ratri nighel",
"Tu?",
"2 tarkheparyant",
"Kiti divs ahe tu ghari ?",
"Udya shivpuri la jaychay",
"Jaato",
"Zandu balm lavto ani zopi jaate",
"Hat pay dhuto",
"Dukhtay",
"Doka dukhrltoy",
"Bar jaude",
"Mazyasobt kshala",
"Lagn tuzyasobat",
"Kay mahit asel kuni Brahmin",
"Nope",
"Lagn pn tichya sobtch kr",
"Will have sex with her",
"ð³",
"But what if she is more beautiful than me nd u like her",
"ð",
"Ho chalu ahe",
"Aaj tr 4mbps cha speed hota mast",
"Fakt net chalte",
"Mahit nahi..ekda pn nahi lagla aaj paryant",
"Bdw period chalu aahet?",
"Call ka nahi lagat ye",
"Kaskay",
"Ha nahi lagla tar to lavel",
"Call lagla asta tr itke divs call idea ch bill kshala bharal asat",
"Mala pan pahije no jio vala",
"Mag mystery kalel",
"Call tar kar",
"Hat be...me tula swapnat pn handsome nahi mhannar",
"Call kar tyavrun",
"Mala aata doubt yetoy tuzach aasel mhanun msgg",
"Malach nahi mahit no",
"?",
"Tuza jio cha no kay aahe",
"Screenshot ghetla na",
"Abe te fb messenger cha aahe ivon",
"Photo tr mazach ahe",
"Ka tuch aahes",
"Tula mahitiye ka kon aahe hi",
"Gay ?",
"Kskay ?",
"Abe porgach aasel ekhada",
"Apla tharlay na no regrets",
"Try tr krun bagh",
"Tuzyapeksha nasel",
"Jau de",
"Tula avdli tr",
"Hot mulgi nighali tr",
"Nope v4 pan nahi kela",
"Mala nahi sangital",
"Tula sangital ka kon ahe ?",
"Kal i think",
"Mala pan ala hota",
"Acha",
"Unknown no vrun msg ala hota.. someone likes u",
"Bol",
"Acha aik",
"Ohh",
"11th 12 th cha",
"Akshay thakare",
"Ani kontya mitrala bhetayla gela hota ?",
"No story",
"Me aikal ki bakwas ahe",
"Vahini",
"Chulat bhau",
"Me rahul",
"Bdw aaj ae dil hai mushkil la gelo hoto",
"Frnds wala",
"Konta",
"Tu maza msg vachla nahi ka ?",
"Acha",
"So no bhau beej",
"Saglya aply aply gavi aahet",
"Aata ithe nahi alyakunich",
"Bahin kon ?",
"Bahin udya ovalti",
"Baki nahi mahit",
"Mag amhala pan",
"Abe aaie babala ovalti",
"Kalal tumchyat asa krtat pn accept nahi karu shakat na..bahinine ovalayla tr bhaubij aahe..mg aaj kshala",
"Its so difficult that u couldnt understand",
"Wow",
"She can understand all this",
"Mhanun kakuna Brahmin mulgi havi ahe",
"1000/- rs aadhich boli keli aaie ne",
"Bahin asel tar ti pn",
"Nahi aaie ovalati amhala",
"Amchyat fakt husband la ovaltat padvyala",
"Ka strange",
"Rohit",
"Gn",
"Anyways",
"Strange",
"Ho",
"Padvyala tumchyat mulala ovaltat ?",
"Visarlo hoto thanks for calling",
"Acha",
"Aaie ghari vat pahat hoti ovalnyasathi",
"Time kalala nahi",
"Aalo tuza call cut kelyavr",
"Tu mitrakade hota na ?",
"Abe msg vachalach navta tuza",
"ð",
"Me kevha mhanali ki imp ahe",
"I hate u",
"Gn",
"Mala waatla kahi imp aahe",
"Bbye",
"Msg ka kela ?",
"Okk",
"Katti ahe me",
"Kay",
"Hey",
"ðð»",
"ðð»",
"Der ?",
"ð",
"ðð»",
"Sang na",
"Ggggnnnnn",
"ðð»",
"Kharch kahich nahi ?",
"U suck",
"Sakali lavkar uthloy",
"Ani zop yetiye aata mala",
"Nothing",
"So what if v modify que like most romantic moment of ur life",
"Acha",
"Let it be",
"She called u 15 days before nd u didn't hang up..u told her what u had for dinner",
"Sheetal pan nahi msg kaarat aata",
"Bye",
"Unlike ur case he doesn't exist in my life anymore",
"Nd bdw gn",
"So plz understand",
"Aga mala asa chatting madhe nahi sangata yet",
"Tula sagal mahitiye...aani vicharal tari me ragat na yeta sangte",
"Ani amchya peksha jastch hota tumcha",
"Tuzya ani sumit baddal",
"Me v4 to ka",
"Kay chaluye tuza",
"I know",
"Aata tu net band krnar",
"Abe yar",
"Chhan",
"Aala rag ?",
"Gn",
"Ani mhne romantic nahi",
"Come on u wrote letters...",
"Navta asa kahi",
"Ugi dusra kashala kadhto",
"Most romantic moment kdhi vicharal",
"Apla bol na",
"Garaj nahi na ga",
"Sheetal baddap",
"3 da",
"Aajchya aaj 2 da zala",
"First time vicharal ha que",
"Nd bdw it doesnt makes me happy",
"But irritating by asking same que is",
"Or things which made u happy",
"It isny",
"Is it wrong if I try to know u",
"Pagal aahe ka be tu",
"I was just trying to know",
"Is it bcoz she didn't called u",
"Aga apla changla bolna suru astana ticha nav ka kadhtiye",
"Rag yenyasarkh kay ahe ?",
"Mala ragat anaychay ka?",
"Ka ticha nav kadhtiye",
"None",
"What is d most romantic memory of u n sheetal or Shraddha",
"Bol",
"Bop",
"Boo",
"Busy ?",
"Rohit",
"Kahitari memorable kraych hot",
"Me kahich planning nahi karu shkli ani ek plan hota to pn fail zala mhanun",
"It was just for ur bday",
"Mala tyat tevdha kahi interest nahiye",
"Sex wala",
"Aapn sobat astanacha time athav",
"Aapoap jail",
"Help me",
"I don't know how to move on",
"I m stuck in moment when I saw that dead thing of my baby..I felt like I killed my baby..it's d most painful memory of my life.",
"Ho",
"As a frnd ek help krshil",
"Gn",
"Gn",
"Rohit",
"I want baby",
"ð",
"But I m not having baby",
"Me decide kel hot ki mulgi zali tr nav ananya thevel",
"Rupal",
"Nahi ripal",
"As a frnd vicharat ahe",
"Do u still have feelings for her ?",
"Nahi",
"Ragavla ?",
"Garajach nahiye tichyabaddl bolaychi",
"Aaik rupal tula sangitla na ticha topic nako kadhat jau",
"She is moving on",
"Ka",
"Tula missing missing vatal asnar na",
"Nahi ala kharach",
"I don't believe it",
"Nahi",
"Call ?",
"Nahi",
"Sheetal cha msg ala?",
"K",
"But it's true na ?",
"Khup senti martiye",
"Kahi nahi",
"Kay zal",
"Hm",
"Gn ?",
"Aapan ekte yeto aani jato pn ektech..ani journey pn aaplyala swatach krav lagto..lok ugich romantic movies baghun swapn pahayla lagtat..it's all myth.",
"Kahi nahi",
"Mag",
"Maza sadhya premavr agodr sarkha vishwas rahila nahiye",
"Acha",
"Bolayla kay jate be..jyala dukhte tyalach kalat",
"Its natural",
"Diwali kharab honyasarkha",
"Tyat kay itka",
"Bye",
"Apan nantr bolu..ugich tuzi Diwali kharab nako..",
"Aai tension mdhe aali mala asa ka hotay..bichari najar utarvat ahe",
"I wanna be a guy then I don't hv to go through this",
"U don't understand manu..each n every body part hurts badly",
"Are tu meli tar maza kasa hoil",
"Asa vatat ki it's better to die",
"Goli ghetli tari pain kami hot nahi",
"So hoil tras",
"First time normal aalet na",
"This never happened before",
"Ale ka",
"Unbearable pain hot ahe",
"Periods",
"Zala maza j1",
"Kay zala be",
"Gn",
"Anyways don't wanna talk to anybody",
"I wish me mulga asayla havi hoti..life kiti easy aste..no mood swings..no pain",
"I really hate being girl",
"Ani ata bhaubijela Puja pn nahi krta yenar",
"I really wanted it u know...I feel sad when I see kids",
"There's a good news for you...u r not going to be a father.",
"Ok",
"Nantr",
"Namtr",
"Photo pathvtoy",
"Bbye",
"Jevan kartoy",
"Aapn baghitla hota na jeans wala shirt",
"Ani dress ghetla",
"Asach",
"Nope",
"Anything special ?",
"Kskay ghetla suddenly ?",
"Nice",
"Black color",
"3gb ram 32 gb internal vala",
"Ok",
"Net vr kar search",
"Specifications ?",
"15000/-",
"Amazon vrun",
"Mobile moto g4 plus ghetla",
"Nehmi sarkh",
"Kasa zala lakshmi pujan",
"Kay zala bol ki",
"Gn",
"Ok then",
"Acha",
"Ani nantr pora aple sagle",
"Bhetayla gelo hoto aadhi family friends",
"Kuthe hota",
"Aata alo ghari",
"Bol gaa",
"Konta ?",
"Order kela",
"Mobile ghetla",
"Hello",
"ðð»",
"There ?",
"I never asked u to be like me",
"If u love someone, u'll do each n every thing to keep them with u...but while doing that if u r thinking about other things then those things r more imp nd u don't love that person really",
"but cannot be like u say",
"thats for sure",
"i love u",
"I'll help u decide",
"It's simple yar.. either u love someone or u don't..there is no maybe.",
"u r getting these weird  questons",
"rupal i dont know",
"?",
"Do u*",
"So give up on me ?",
"yup",
"Is it best u can do ?",
"Was it ur best try ?",
"so me kahi karu shakat nahi",
"but tula te sufficient nahi vatat",
"me prayatna kartoy",
"aaik",
"?",
"I beg you.. please do something about it nd if u can't then tell me clearly then I'll move on",
"Ani break up karan mazyasathi evdh easy asta tr 1 vrsh agodrch kel asta",
"This is not bad mood..it's a practical issue in our relationship..this is not going to chng until n unless u do something about it",
"then u only take action",
"if this is not going to happen in future",
"that this bad mood of yours will get over soon",
"i m thinking",
"its not blame game",
"no rupal u only decide",
"U hv to decide something bcoz this is killing me",
"nothing",
"So what u hv decided ?",
"But if this time it breaks, I won't do anything",
"Nd u know what ? In our relationship I always made d first move..to propose or to patch up or to chnge myself, etc etc",
"Khup prob ahe manu...u don't even care",
"Well at first that was d only best thing",
"mutual understanding is",
"interest is never the thing that is causing this trouble",
"I don't think u r interested in me anymore..",
"So plz say",
"What do u want to do ?",
"I m really tired and exhausted..I hv been to make this works from almost 1 year..",
"N listen",
"Please be calm",
"laptop madhun kelay chalu",
"ðð»",
"There ?",
"You missed a call from Rupal.",
"mobile chi charging utarliye",
"Gn baby",
"ð",
"Love you baby",
"You called Rupal.",
"Maza pn msg nahi hotay send",
"Der ?",
"WhatsApp slow ahe yar",
"Acha",
"Whatsapp vr ye",
"Taunt hota ka ?",
"Mala kalal nahi kay mhanala",
"Parat fb online mhanun disashil",
"Kay",
"Ye",
"Wa",
"ðð»",
"Ok",
"5 min madhe mala zopaychay",
"nahi ragvat",
"Kaku ragvtil",
"skype vr ye",
"Chukun lagla",
"You missed a video chat with Rupal.",
"Sure ?",
"nahi",
"Frankly sang",
"Do u want me to marry him",
"kahi nahi hot",
"jaa",
"abe talu nako",
"Kay karu ?",
"okay",
"I don't know but I doubt",
"?",
"tyana yenar aahe ka",
"acha",
"Me diwalila ghari jat ahe..tevha Gaurav cha ghari bolval ahe",
"kay practical issue",
"?",
"??",
"ðð»",
"Let me know whenever u r ready to discuss",
"Ek serious practical issue ahe",
"But u can do it with others with my permission",
"okay",
"N v r not doing it again",
"acha",
"I just want you to know one thing..I trust you beyond everything..If it ever gets break, I won't be able to trust anyone again. U r my life now. Please remember that.",
"Speechless",
"just it should inside u",
"anything",
"all",
"What do u like ?",
"acha",
"Chidvat hote",
"Asch mhanale",
"Abe kalal nahi",
"me kabhi upar kabhi tu uper",
"tyana kasa kalala",
"Asa mhant hote",
"Jijaji kabhi upar kabhi niche",
"kashyavr",
"Pori double meaning marat hotya",
"home",
"are fb ch na",
"Fb vr kay mhanali me",
"are fb",
"Kay krtoy ?",
"5 mins",
"Zopla nahi ?",
"love u too",
"I love you",
"gn",
"Gn Manu",
"Zop",
"Tula chance dete tevha tu jat nahi mg nantr jato tevha mala khup tras hoto",
"gn rupal mala zop yetiye",
"I mean it",
"I m serious manu",
"abe zop na ka bore kartiye",
"Tuzya gharche khush hotil",
"Tu Shraddha sobt patch up kr..ti same cast chi ahe",
"Ani mala tyana hurt kraych nahiye",
"I was saying that v should stop seeing each other..ur parents don't like me.",
"hmm",
"I won't let u go down",
"?",
"/",
"why",
"U know that is impossible",
"with u",
"â",
"One last thing",
"gn",
"nahi aata fb band kartoy",
"Gn",
"Anyways seems like u r busy",
"ð",
"nope",
"Krshil ?",
"achaa",
"Ugich bhandan nako",
"Relatives ahet tr kadhi na kadhi bhet hoelch",
"Ekda nit bolun sort out kara",
"Shraddha la call kr ani bhetayla bolav",
"/??",
"Ek suggestion ahe",
"I will try to improve",
"hm",
"Aik",
"Acha",
"mobile kharab hote",
"kahi nahi",
"Toilet mdhe mob pdlyavr kay hote ?",
"kay boltiye be tu",
"Sheetal sobt try kr ekda mg mala sang mala kay improve krta yeil",
"i wanna do it again",
"krtoy me",
"abe majja",
"I think u should try with some experienced person",
"Seems like v r on same boat",
"okaaayyyyyyyyy",
"Not at all",
"do u ??????",
"never",
"nop",
"U wanna do it again ?",
"yah",
"But it was awesome",
"like our sex",
"tiresome",
"How was ur day",
"okay",
"Just wanna hold ur hand",
"Not for that dude",
"brush cover",
"okay",
"I really miss you",
"Rohit",
"nahi",
"Tu zopat nahi?",
"Acha",
"so laptop madhe fb kelay chalu",
"Nahi",
"net",
"ek tar mobile band padtoy nahi tar",
"abe zopli ka",

]);

